package raf.bolnica1.laboratory.domain.constants;

public enum Profession {
    MED_SESTRA,
    SPEC_BIOHEMICAR,
    SPEC_GASTROENTEROLOG,
    SPEC_GINEKOLOG,
    SPEC_ENDOKRINOLOG,
    SPEC_KARDIOLOG,
    SPEC_NEUROLOG,
    SPEC_NEFROLOG,
    SPEC_PSIHIJATAR,
    SPEC_PULMOLOG,
    SPEC_UROLOG,
    SPEC_HEMATOLOG,
    SPEC_HIRURG
}
